import type { Metadata } from "next";
import "@/app/styles/base.all.scss"
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import { Providers } from "./providers";


export const metadata: Metadata = {
  title: "Roya Technology",
  description: "Generated by SOFTFOUNT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
