# Generated by Django 4.2.16 on 2024-09-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoyaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20)),
                ('instagram_account', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_account', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_account', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
