# Generated by Django 4.2.16 on 2024-09-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoyaApp', '0005_project_description_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
