# Generated by Django 4.2.16 on 2024-10-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoyaApp', '0011_project_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='long_description',
            field=models.TextField(default='.'),
        ),
    ]
